language: r
cache: packages
latex: false
fortran: false
pandoc: false

matrix:
  include:
    - dist: precise
    - dist: trusty
    - dist: xenial
    - dist: xenial
      addons:
        apt:
          sources:
            - sourceline: 'ppa:jeroen/poppler'
          packages:
            - libwebp-dev
            - libpoppler-cpp-dev
            - poppler-data
    - os: osx
      brew_packages: poppler
    - os: osx
      osx_image: xcode7.3
      disable_homebrew: true
      before_install: sed -i.bak 's/-isysroot /-I/g' $(R RHOME)/etc/Makeconf

addons:
  apt:
    packages:
      - libwebp-dev
      - libpoppler-cpp-dev
      - poppler-data

notifications:
  email:
    on_success: change
    on_failure: change

# Prevents Travis timeout for building libpoppler
before_install:
  - (while true; do echo 'Ping? Pong!'; sleep 500; done) &
