language: r
cache: packages
latex: false
fortran: false
pandoc: false

matrix:
  include:
    - dist: precise
    - dist: trusty
    - dist: xenial
      r_packages: covr
      after_success: R -e 'covr::codecov()';
    - os: osx
      brew_packages: poppler
    - os: osx
      osx_image: xcode7.3
      disable_homebrew: true

addons:
  apt:
    packages:
      - libwebp-dev
      - libpoppler-cpp-dev
      - poppler-data
      - valgrind

notifications:
  email:
    on_success: change
    on_failure: change

# Prevents Travis timeout for building libpoppler
before_install:
  - (while true; do echo 'Ping? Pong!'; sleep 500; done) &
